import type {ISettings} from "@/types/ISettings";

export const defaultSettings:ISettings = {
    filenameTemplate: 'Timelogs %s',
    dateFormat: 'dd.mm.yyyy',
    dateRangeFormat: 'dd.mm?.yyyy? - dd.mm.yyyy',
    closeFiltersOnApply: true,
    checkForUpdateIntervalMinutes: 10,
    storeOnControlEnter: true,
    clearTimeLogOnStore: true,
    showParsePreviewOnType: true,
    keepOriginalLogOnEdit: false,
    defaultDuration: 30,
    hourThreshold: 5,
    defaultRate: 255,
    currencyFormat: "%s €",
    rateIncludesTax: true,
    tax: 0,
    showCostColumn: true,
    showProjectColumn: true,
    showSourceColumn: true,
    showClientColumn: true,
    showTaskColumn: true,
    showDupeButton: true,
    defaultClient: "",
    defaultProject: "",
    defaultTask: "",
    defaultSource: "",
    deviceName: null,
    deviceId: null,
    syncEnabled: true,
    syncSettings: true,
    defaultView: "month",
    showHelpIcon: true
};